apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{NAMESPACE}}

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - virtualservice.yaml
  - destinationrule.yaml

commonLabels:
  app: {{APP_NAME}}
  framework: react
  managed-by: cloudeefy

images:
  - name: {{REGISTRY}}/{{TENANT}}/{{IMAGE_NAME}}
    newTag: latest
